"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from pathlib import Path
import environ
import os

# ----------------------------------------------------------------
# GENERAL
# ----------------------------------------------------------------
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    # set casting and default values
    DJANGO_DEBUG=(bool, False),
    DJANGO_SECRET_KEY=(str, 'django-insecure-and-not-secret-key'),
    DJANGO_DATABASE_DEFAULT_ENGINE=(str, 'django.db.backends.postgresql'),
    DJANGO_DATABASE_DEFAULT_NAME=(str, 'website'),
    DJANGO_DATABASE_DEFAULT_USER=(str, 'django'),
    DJANGO_DATABASE_DEFAULT_PASSWORD=(str, ''),
    DJANGO_DATABASE_DEFAULT_HOST=(str, 'localhost'),
    DJANGO_DATABASE_DEFAULT_PORT=(str, '5432'),
)
# reading .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# ----------------------------------------------------------------
# DEVELOPMENT AND PRODUCTION
# ----------------------------------------------------------------
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DJANGO_DEBUG")

ALLOWED_HOSTS = env("DJANGO_ALLOWED_HOSTS").split(" ")

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True


# ----------------------------------------------------------------
# APPLICATION
# ----------------------------------------------------------------
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'fontawesomefree',
    'website'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'website', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# ----------------------------------------------------------------
# DATABASE
# ----------------------------------------------------------------
# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env('DJANGO_DATABASE_DEFAULT_ENGINE'),
        'NAME': env('DJANGO_DATABASE_DEFAULT_NAME'),
        'USER': env('DJANGO_DATABASE_DEFAULT_USER'),
        'PASSWORD': env('DJANGO_DATABASE_DEFAULT_PASSWORD'),
        'HOST': env('DJANGO_DATABASE_DEFAULT_HOST'),
        'PORT': env('DJANGO_DATABASE_DEFAULT_PORT'),

        'CONN_MAX_AGE': 30,             # https://docs.djangoproject.com/pt-br/4.1/ref/settings/#conn-max-age
        'CONN_HEALTH_CHECKS': True,     # https://docs.djangoproject.com/pt-br/4.1/ref/settings/#std-setting-CONN_HEALTH_CHECKS (New in Django 4.1)
    }
}

# ----------------------------------------------------------------
# PASSWORD VALIDATION
# ----------------------------------------------------------------
# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ----------------------------------------------------------------
# INTERNATIONALIZATION
# ----------------------------------------------------------------
# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ----------------------------------------------------------------
# STATIC FILES
# ----------------------------------------------------------------
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# Sometimes Django apps are deployed at a particular prefix (or “subdirectory”) on a 
#   domain e.g. https://example.com/my-app/ rather than just https://example.com.
#   FORCE_SCRIPT_NAME sets this subdirectory.
# https://docs.djangoproject.com/en/4.1/ref/settings/#force-script-name
# https://whitenoise.evans.io/en/stable/django.html#deploying-an-application-which-is-not-at-the-root-of-the-domain
FORCE_SCRIPT_NAME = "/"

STATIC_URL = FORCE_SCRIPT_NAME + 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'website', 'static'),
]

# Whitenoise - Simplified static file serving.
# https://pypi.org/project/whitenoise/
# https://whitenoise.evans.io/en/stable/django.html

# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-STORAGES
# A dictionary containing the settings for all storages to be used with Django
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        #"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",   # default storage engine.
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",   # Whitenoise: Add compression and caching support
        #"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",          # Whitenoise: Add compression but not caching support
    },
}

# ----------------------------------------------------------------
# DEFAULT VALUES
# ----------------------------------------------------------------
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
